### ISSUE TITLE
use strict mode

### ISSUE THREAD

**Issue by dennis2k** [sascha245/vuex-simple#8]
-  **I'm submitting a ...**
[ ] bug report
[x ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

-  **Summary**

*  **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

Hi @sascha245  - first off, great implementation of vuex type support in stores and in components. It seems to be hard for must libraries to make this work great.
However we need to run our store with strict mode = false for performance concerns - are you working on implementing this as a configurable parameter or shall i do this in a pull request ?

**Comment by sascha245** [comment]
Hi @dennis2k,

Yes, I am currently working on better store configurability along with some other code improvements. 
It should be added during this week in version 1.2.0, but if you need it immediately, you can use the following little "hack" to disable strict mode as long as you are waiting for the next version:

```ts
...
// before storeBuilder.create()
const storeBuilder = getStoreBuilder();
(storeBuilder as any)._options.strict = false;
...
```

I will notify you here once the version is available, so that you can do it in a cleaner and more stable way if you wish.

**Comment by dennis2k** [comment]
Very nice - I'll use the hack for now. Thanks :)

**Comment by sascha245** [comment]
Hi @dennis2k ,

1.2.0 is now out with #10 . I added a section in the README concerning store configuration, but here a short extract:
```ts
const storeBuilder = getStoreBuilder();
storeBuilder.initialize({
  modules: {},
  state: {},
  strict: false
})
// load your modules and create store
// ...
```

I wish you a nice day,

Sascha
